# Generated by Django 2.0.6 on 2018-08-31 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('completed', models.BooleanField()),
                ('review_completed', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cell_number', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('active_orders', models.CharField(max_length=500)),
                ('history', models.CharField(max_length=1000)),
                ('payment_info', models.CharField(max_length=1000)),
                ('account_balance', models.IntegerField()),
                ('verified_provider', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Valid_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('ve', 've'), ('sq', 'sq'), ('ca', 'ca'), ('pa', 'pa')], default='ca', max_length=2)),
                ('card_number', models.CharField(default='', max_length=16)),
                ('name_on_card', models.CharField(default='', max_length=100)),
                ('expiration_date', models.CharField(default='', max_length=8)),
                ('ccv', models.CharField(default='', max_length=3)),
                ('handle', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_profile.Profile'),
        ),
    ]
