# Generated by Django 2.0.6 on 2018-08-31 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180831_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='end_time',
            new_name='dropoff_end_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_time',
            new_name='dropoff_start_time',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
